### ISSUE TITLE
Plugin not loading properly

### ISSUE THREAD

**Issue by ramzh** [ccdc06/metadata#1]
When uploading the plugin specyaml.pm the following shows up:

> Couldn't require LANraragi::Plugin::Sideloaded::SpecYAML : Can't locate LANraragi/Plugin/Sideloaded/SpecYAML.pm in @INC (you may need to install the LANraragi::Plugin::Sideloaded::SpecYAML module) (@INC entries checked: /home/koyomi/perl5/lib/perl5/5.38.2/x86_64-linux-thread-multi /home/koyomi/perl5/lib/perl5/5.38.2 /home/koyomi/perl5/lib/perl5/x86_64-linux-thread-multi /home/koyomi/perl5/lib/perl5 /home/koyomi/lanraragi/script/../lib /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at /usr/local/share/perl5/site_perl/Module/Runtime.pm line 314. at /usr/local/share/perl5/site_perl/Module/Pluggable.pm line 31.

**Comment by ramzh** [comment]
```services:
  lanraragi:
    container_name: lanraragi
    image: difegue/lanraragi:latest
    volumes:
      - /ssd/appdata/lanraragi/database:/home/koyomi/lanraragi/database
      - /ssd/appdata/lanraragi/public/temp:/home/koyomi/lanraragi/public/temp
      - /ssd/appdata/lanraragi/plugins:/home/koyomi/lanraragi/lib/LANraragi/Plugin/Sideloaded
      - /pool/bookshelf/thumbnails:/home/koyomi/lanraragi/public/thumb
      - /pool/bookshelf/ccdc06:/home/koyomi/lanraragi/content
    ports:
      - "3001:3000"

Docker set up

**Comment by ramzh** [comment]
When uploading the plugin:

```[2024-11-16 15:11:29] [Plugin Upload] [info] Uploading new plugin specyaml.pm to /home/koyomi/lanraragi/lib/LANraragi/Plugin/Sideloaded/specyaml.pm ...
[2024-11-16 15:11:29] [Plugin Upload] [error] Could not instantiate plugin at namespace LANraragi::Plugin::Metadata::specyaml!
[2024-11-16 15:11:29] [Plugin Upload] [error] 

![image](https://github.com/user-attachments/assets/9743e42d-7d01-40d8-b235-2f3de74dd40f)

**Comment by ccdc06** [comment]
I don't have much experience with debugging Lanraragi but I'll try...

I have never been able to get the plugin web uploader to work because of permission problems, but since you have set up a sideload plugin directory, you can install the plugin by copying the .pm script into that directory.

The script filename is named in lowercase in the repo but I had to rename it from `specyaml.pm` to `SpecYAML.pm` to get it to work. Probably this explains that first error `Can't locate LANraragi/Plugin/Sideloaded/SpecYAML.pm`.

**Comment by ramzh** [comment]
Goit it to load by renaming as you pointed out correctly and mapping the sideloaded folder as in the docker-compose.

Now In think the only issue is the Batch Operation crushing, but that's a LRR issue. Thanks!
